### ISSUE TITLE
Incorrect speed on 30FPS

### ISSUE THREAD

**Issue by STak4** [unai-d/Unai.VITC#1]
Hi.
Thanks for the nice tool.

I noticed that bit faster output at the 30fps.

The default duration is 1m40s while the output is 1m23s.
The result of readvitc by ffmpeg is also bit faster.

An example of command is below.
`Unai.VITC.exe | ffmpeg.exe -f rawvideo -video_size 90x1 -pixel_format gray -framerate 30 -i - -f mp4 -c:v h264 -pix_fmt yuv420p -vf scale=360:4:flags=neighbor vitc90x4-30fps.mp4`

At 25fps, works will fine.

Are there any possible causes?

Thanks.

**Comment by unai-d** [comment]
Hi.

You have to specify the framerate to the VITC program:

`Unai.VITC.exe -fps 30`

Also, the fact that your video had a length of 1 minute and 23 seconds is because the program takes into account the number of total frames regardless of the framerate. The default duration is actually [2500 frames](https://github.com/unai-d/Unai.VITC/blob/4f92abd3b82da38acc81cf0af2a81c5eb39e9369/VITCLine.cs#L25), which at 30 FPS gives a video of 1 minute and 23.3 seconds.

**Comment by STak4** [comment]
@unai-d 
Thanks for the response.

Okay, I didn't know that number of frames is constant.
Thank you!
