### ISSUE TITLE
No complied version / Executable

### ISSUE THREAD

**Issue by SimeJah** [unai-d/Unai.VITC#3]
Dear developers,
I am a noob when it comes to programming and I have no clue how to use these c# files.
But I REALLY need this tool for a large scale event where I will do video mapping. (I am a VJ)
If anyone can compile this to an executable for either Mac or Windows that I can use, I would be forever grateful!

**Comment by davorg** [comment]
[Some context](https://www.reddit.com/r/github/comments/108d9ql/need_help_running_this_toold_from_github/)

**Comment by unai-d** [comment]
[Unai.VITC-win-x64.zip](https://github.com/unai-d/Unai.VITC/files/10391605/Unai.VITC-win-x64.zip)

There you go. I'm assuming you're using 64-bit Windows. Make sure you installed both .NET Core 3.1 and FFmpeg.

Check that FFmpeg and my program are accessible from the command prompt:
- Download both FFmpeg and my program with the provided link.
- Open a command prompt window (open the Start menu and start typing "Command prompt" and click on it if it appears)
- On the command prompt, type `explorer` and press Enter. A window will appear showing the contents of the folder where you need to place both `ffmpeg.exe` and `Unai.VITC.exe` (also copy all DLLs and supplemental files that may exist alongside the EXEs). AFAIK FFmpeg doesn't need any DLLs.
- Check that FFmpeg is accesible by typing `ffmpeg` and pressing Enter. If you don't receive any error about "command not found", repeat this step typing `Unai.VITC.exe` instead.

Once all of that is done, you can generate a simple VITC with this command from the `README` file (I modified it so it finishes quickly). Copy-paste all of the following and press Enter.
```
Unai.VITC.exe | ffmpeg.exe -f rawvideo -video_size 90x1 -pixel_format gray -framerate 25 -i - -t 10 -f mp4 -c:v h264 -pix_fmt yuv420p -vf scale=360:4:flags=neighbor my-vitc.mp4
```

A file named `my-vitc.mp4` should appear on the same window you placed all of the programs.

**Comment by SimeJah** [comment]
Yes I got it working Thank you so much for your involvement and fast reply! Thank you so much for publishing this tool for free! Amazing! :D

**Comment by unai-d** [comment]
You're welcome! :)

**Comment by harrypm** [comment]
@unai-d I would recommend making this into a release so people don't run into this issue again and find it on the side tab/readme.

I saw the initial comment from @SimeJah on my [VITC Reddit](https://www.reddit.com/r/ffmpeg/comments/tnd3gv/vitc_reading_exporting_to_file_and_embedding/) post, hello from the [VHS-Decode](https://github.com/oyvindln/vhs-decode/wiki/) wiki btw your tool has been very useful for the R&D of embedding VITC into the .TBC format for decode testing and live playback to S-Video/Composite.

**Comment by unai-d** [comment]
You're right. I will try to get the binaries uploaded and available on the Releases tab. It has been 2 years since the last commit and I think this little program deserves an update.

Also, I'm glad my program came in handy for all of you. I knew about the VHS-Decode project before and given the size of it, I assumed you already had tools for these kind of things.

**Comment by SimeJah** [comment]
Hello @unai-d I have one more question. I am new to github so sorry if this is the wrong place to ask.. (I could not find a DM section or something)

Is it possible to make a 50/60 fps version? The visuals I am using it with are now lagging as they are synced to 25fps. 
Thank you in advance!

**Comment by unai-d** [comment]
I'm afraid that's not possible, since VITC can only represent a maximum of 39 frames. The bits that could be used to represent higher numbers are already reserved to represent flags (bit 14 and bit 15, to be exact).

One solution would be to generate an interlaced VITC signal (that's `-i` on the command line for version 1.0). Then, you can mix each VITC line to its respective progressive frame on the video. If you're using analogue devices to sync one or multiple video signals, then this trick doesn't work, since those systems are always interlaced.

### Example for 50 FPS
Generate it with
```
Unai.VITC.exe -fps 25 -i
```

![vitc-field-001](https://user-images.githubusercontent.com/70072019/213676489-bfb1a495-2a20-477d-8a96-95d7186aa978.jpg)
Frame 0, VITC reads frame 0, field 0.

![vitc-field-002](https://user-images.githubusercontent.com/70072019/213676657-01c930be-8fc8-4404-958a-75519ba49c33.jpg)
Frame 1, VITC reads frame 0, field 1.

![vitc-field-003](https://user-images.githubusercontent.com/70072019/213676948-4d76c543-3036-44e8-9c5a-b9a0b6ba568d.jpg)
Frame 2, VITC reads frame 1, field 0.

![vitc-field-004](https://user-images.githubusercontent.com/70072019/213677130-d7ed7dec-d4cd-494f-9cfe-d656cf0b29a5.jpg)
Frame 3, VITC reads frame 1, field 1.

![vitc-field-005](https://user-images.githubusercontent.com/70072019/213677261-39a0b714-df54-47a0-8973-a92a8c2eb8db.jpg)
Frame 4, VITC reads frame 2, field 0.

When reaching one second:

![vitc-field-049](https://user-images.githubusercontent.com/70072019/213677573-b4390889-99a0-4b26-9654-5743bf9fb049.jpg)
Frame 48, VITC reads second 0, frame 24, field 0.

![vitc-field-050](https://user-images.githubusercontent.com/70072019/213677866-52fdfed0-9660-41e7-bcb0-e09707fff7c6.jpg)
Frame 49, VITC reads second 0, frame 24, field 1.

![vitc-field-051](https://user-images.githubusercontent.com/70072019/213678002-3bb8a2d9-cdc7-4143-96e1-8175d060e921.jpg)
Frame 50, VITC reads second 1, frame 0, field 0.

**Comment by harrypm** [comment]
Since I have notifications on for the whole repo I guess I'll drop this here.

SMPTE TC supports 25/29.97/30/23.97/24 in either progressive or interlaced this goes for LTC and VITC. 

29.97DF and 30DF **Drop Frame** are also in the spec

However, the LTC side has expanded support for 50/59.97/60 fps rates in recent hardware [via duplication](https://support.timecodesystems.com/hc/en-us/articles/360022510452-Can-I-record-at-higher-frame-rates-) though SMPTE Digital TC is normally embedded into all video files based on internal time crystal TC or external audio sync on even entry level cameras nowadays its pretty accurate for 6-hour events.

@SimeJah I genuinely wonder what setup you're using and or why going VITC instead of audio sync or digital TC?
